<a href="https://colab.research.google.com/github/MikeDaBossss/Job_Board_scraper/blob/master/simpyhired.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from urllib.request import urlopen as uReq
from bs4 import BeautifulSoup as soup
import re
#f = urllib.request.urlopen(link)
for i in range(0,200,10):
  jobs_url = 'https://www.indeed.com/jobs?q=data+analyst&l=minneapolis%2C+MN&start=i'

  #opening connection and grabbing the page
  uClient = uReq(jobs_url)
  page_html = uClient.read()
  uClient.close()

  #html parsing
  page_soup = soup(page_html, "html.parser")

  #grab all divs with a class of result
  results = page_soup.findAll("div", {"class": "result"})
  print(len(results))

  filename = '/content/drive/My Drive/jobs_indeed.csv'
  f = open(filename, "w")

  headers = "Title, Company, Location, Experience, Link \n"

  f.write(headers)

  for result in results:
      title = result.findAll('div', {'class':'title'})
      title = title[0].text.strip()
      print(title)

      company = result.findAll('span', {'class':'company'})
      company_name = company[0].text.strip()
      print(company_name)

      try:
        location = result.findAll('div', {'class':'location'})
        location_name = location[0].text.strip()
      except:
        None
      #print(location)

      summary = result.findAll('div', {'class':'summary'})
      job_summary = summary[0].text.strip()

      #exp = result.findAll('span', {'class':'experienceList'})
      #experience = exp[0].text.strip()

      link = result.a['href']
      job_link = ("https://www.indeed.com" + link)

      try:
        salary = result.findAll('span', {'class':'salary-snippet'})
        salary = salary[0].text.strip()
      except:
        None

      print(title)
      print(company_name)
      print(location_name)
      print(job_summary)
      #print(experience)
      print(job_link)
      print(salary)

      f.write(title + "," + company_name + "," + location_name + "," + "," + job_link + "\n")

  f.close()

In [25]:
#salary = result.findAll('span', {'class':'salary-snippet'})
#salary = salary[0].text.strip()
from urllib.request import urlopen as uReq
from bs4 import BeautifulSoup as soup
import re
#f = urllib.request.urlopen(link)
filename = '/content/drive/My Drive/jobs_indeed.csv'
f = open(filename, "w")
jobs = ['data+analyst','data+scientist','analyst','business+analyst','data+engineer','machine+learning+engineer','market+research+analyst']
for job in jobs:
  for i in range(0,50):
  #https://www.simplyhired.com/search?q=data+analyst&l=Minneapolis-Saint+Paul%2C+MN&pn=2
    jobs_url = 'https://www.simplyhired.com/search?q=' + job + '&l=Minneapolis-Saint+Paul%2C+MN' + '&pn=' + str(i)
    #print(i)

      #opening connection and grabbing the page
    uClient = uReq(jobs_url)
    page_html = uClient.read()
    uClient.close()

      #html parsing
    page_soup = soup(page_html, "html.parser")

      #grab all divs with a class of result
    results = page_soup.findAll("div", {"class": "SerpJob-jobCard"})
    #print(len(results))

    for result in results:
          title = result.findAll('h2', {'class':'jobposting-title'})
          title = title[0].text
          title = title.replace(',','')
          print(title)

          company = result.findAll('span', {'class':'jobposting-company'})
          company_name = company[0].text
          company_name = company_name.replace(',','')
          #print(company_name)

          try:
            location = result.findAll('span', {'class':'jobposting-location'})
            location_name = location[0].text
            location_name = location_name.replace(',','')
            #print(location_name)
          except:
            location_name = 'Not available'

          summary = result.findAll('p', {'class':'jobposting-snippet'})
          job_summary = summary[0].text
          job_summary = job_summary.replace(',','')
          #print(job_summary)

          #exp = result.findAll('span', {'class':'experienceList'})
          #experience = exp[0].text.strip()

          link = result.find('a', {'class':'card-link'})
          link = link['href']
          job_link = ("https://www.simplyhired.com" + link)

          try:
            salary = result.findAll('span', {'class':'jobposting-salary'})
            salary = salary[0].text
            salary = salary.replace(",", "")
          except:
            salary = 'Not available'

          #print(type(title))
          #print(type(company_name))
          #print(type(location_name))
          #print(type(job_summary))
          #print(experience)
          #print(job_link)
          #print(type(salary))
          f.write(title + "," + company_name + "," + location_name + "," + job_summary + "," + salary + "," + job_link + "\n")

f.close()

Data Analyst
Capstone Data Analyst
Marketing Data Analyst
Jr. Data Analyst
Pharmaceutical Data Analyst
Junior Business Analyst
Capstone Data Analyst
PLM Data Analyst
Client Data Analyst - KF Institute
Health Data Analyst Job
Data Analyst
Data Analyst
Capstone Data Analyst
Marketing Data Analyst
Jr. Data Analyst
Pharmaceutical Data Analyst
Junior Business Analyst
Capstone Data Analyst
PLM Data Analyst
Client Data Analyst - KF Institute
Health Data Analyst Job
Data Analyst
Data Operations Analyst
Genomics Data Analyst
Data Driven Solutions Analyst
Quality & Performance Improvement Data Analyst
Invoice Processing/Data Analyst
SharePoint & Data Analyst - Management Analyst 3
Analyst Data Intelligence
Analyst Market Research and Data Analytics
Statistician-Data Analyst
HEDIS Data Analyst
Principal Data Analyst
Survey Data Analyst
Data Science Analyst
Master Data Analyst
Business Intelligence Data Analyst
Jr. Business Analyst
Sourcing Data Analyst - Ingredients
Security Data Analyst
Data Analytics Analyst
Business Data Analyst
Regulatory and Quality Data Analyst*
Data Analyst
Data Analyst- Contractor
Data Analyst
Sr Data Analyst
Associate Analyst Data Intelligence
Data Modeler - Database Analyst 4
Senior Data Analyst Analytics
Systems Data Analyst
Systems Data Analyst
Marketing Data Analyst
Principal Analyst - Data Science/ Customer Insights
IT Business Analyst - ITS3
Data Analyst Operations Analysis and Performance (OAP)
Senior Data Analyst
Senior Data Analyst – Minneapolis MN or Charlotte NC
Marketing Data Analyst
Sr Business Data/Process Analyst
Sr. Consumer Data Privacy Analyst
Data Warehouse Analyst Intern
Business Analyst Information Technology
Principal Data Analyst
Research Analyst
Data Analyst & Report Writer
Manufacturing & Supply Chain Data Analyst (Maplewood MN)
Business Analyst
Healthcare Business & Data Analyst - Clarity
Business Analyst
Healthcare Data Analyst - Minneapolis
Operations Analyst - Data Focused
Business Analyst
Senior Pharmacy Data Analyst
Business Analyst
Senior Data Analyst Analytics
Oracle Business Analyst
Senior Data Analyst
Informatic Senior Data Analyst
Reporting Analyst
EHSS Data Analyst & System Admin
Intern - Data Science
Business Intelligence Analyst
Entry level Business Analyst/Software Eng
Data Specialist
Business Analyst
Healthcare Business & Data Analyst
Sr. Consumer Data Privacy Analyst
Business Analyst
Business Analyst
Business Analyst
Business Intelligence Analyst
Master Data Management Business Analyst
SQL Developer Data Analyst
SQL Developer Data Analyst
QA Analyst - Data testing
Business Analyst
Business Intelligence Data Analyst Lead
Data Analyst & Report Writer - Sales
Healthcare Business/Data Analyst
ERP Business Analyst
Big Data Analytics Intern
IT Business Analyst
Business Analyst II
Senior Data Analytics and Reporting Analyst (Minneapolis MN)
Business Intelligence Data Specialist
Business Analyst - LIMS
Business Process Analyst
Business Analyst
Clinical Data Analyst / Info Consultant
Master Data Management Business Analyst
Statistician-Data Analyst-Summer Intern Associate Development Program 2020
HT Innovation - Business Analyst
Sales Data Analyst
Senior Clinical Data Analyst I
Senior Data Analyst / Business Analysis Consultant
Business Analyst
Business Analyst JDA
Data Science Intern
Sr Data Analyst - Supply Chain
Data Engineering Analyst
Business Analyst
Tech Business Analyst (BHJOB22048_616)
People Analytics Business Analyst
Senior Data Analyst
Business Analyst - Transportation
Data Analyst (Warranty Operations)/Sr. Data Analyst
Business Analyst
IT Business Analyst
Data Management Intern
Associate Strategic Revenue Management (Analytics Data and Models)
Business Analyst - ERP
Business Intelligence Analyst
Business Analyst
Data Governance and Analytics Education Program Director
Data Analytics (Audit) Intern
Sales & Forecasting Analyst
Business Analyst
Business Analyst
Business Analyst Consultant IHR Support
Quality Assurance & Business Analyst
Business Analyst
Business Analyst
Business Analyst with M-WMOS implementation experience
Healthcare Economics Analyst
Business Analyst 3 MSP CSDG
Senior Health Data Analyst
IT Business Analyst
Principal Data Analyst
QA Audit & Test Analyst
Data Center Support Intern
Business Analyst
HRIS Reporting Analyst
Business Intelligence Analyst
Quality Assurance Analyst
Business Analyst IS Intermediate
HIM Systems Analyst (Health Information Management)
Business Analyst 1 - Minneapolis or Houston
Data Analytics Consultant
SAP Business Analyst - FICO
Salesforce Business Analyst
Business Analyst
Business Analyst
Business Intelligence Analyst
Business Intelligence Analyst
Senior IT Systems Analyst - Data Integration Team
Senior Data Warehouse Program Analyst
Business Analyst Intern
Court Operations Analyst II - Business Practices Unit
HR Business Analyst
3M HIS Data Science/Machine Learning Intern
Business Analyst w/ Broker Commissions and Healthcare
Business Analyst
Ecommerce Business Analyst
Business Analyst
ServiceNow Business Analyst
SAP TM Business Analyst
Accounting & Data Analytics Intern (Audit)
Formulary Consultant Business Analyst
Business Analyst (DevOps)
Sr. Product Analyst
Sales Operations Analyst
Jr Business Analyst
Enterprise Risk Adjustment Business Analyst Associate Job
Financial Technology Analyst
IT Analyst Intern
Business Analyst - Developer
IT Advanced Business Analyst - ITS4
Associate Baan Business Analyst
Sr. ERP Business Analyst
Business Analyst II
Technical Business Analyst
Manager Data Analytics - Clinical Decision Support and Analytics Enablement
Sales Operations Analyst - Structural Heart
Benefits Outsourcing Business Analyst - University
Sales Operations Analyst
IT Technical Business Analyst (BA)
Lab Analyst
Business Intelligence Analyst
Business Analyst Team Manager
Business Intelligence Analyst/Data Engineer
ServiceNow Business Analyst
Operations Analyst
Operations Business Analyst
Sr Analyst - Supply Chain Data Capabilities
IT Business Analyst
IT Business Analyst
Rental Services Equipment Analyst
Sr. IT Business Analyst
Digital Business Analyst
Data and Reporting Specialist/National Accounts Coordinator
Technical Business Analyst
Director - System Clinical Data Analytics
Senior Director of Data Analytics
Senior Talent Analyst
Business Analyst for Course Curriculum and Degree Planning Systems
Sr. Business Analyst
Pharmacy Business Analyst
Internship – R&D - Graduate Data Science Intern (Maplewood MN)*
Customer Care Business Analyst
Business Analyst
Infrastructure Business Analyst
Pricing Analyst
Business Analyst/Project Manager
Technical Business Analyst
Business Analyst Team Manager
Financial Systems Analyst 2 - Minneapolis MN
Lead Business Intelligence Analyst
SAP ACM Business Analyst
Business Process Analyst II
Senior Business Analyst
Business Intelligence Analyst
IT Senior Business Analyst - ITS5
Systems Analyst Intermediate
Business Analyst
Procurement Operations Analyst
Senior Analyst Marketing Data Analytics
Environmental Data Specialist Internship
Environmental Data Specialist Internship
2020 - Summer - Consulting Intern - Technology - Data Analysis & Business Intelligence
Business Analyst - Information Technology
Business Analyst Team Manager
IT Business Analyst
Marketing Research Analyst
Lead Business Analyst
Salesforce Business Analyst/Administrator
Business Analyst Pr Job
Business Analyst 4 Core Market
Business Analyst II/III - Enterprise Risk Group
Senior Business Analyst
Manager Business Analyst
Business Analyst Pr Job
Senior Analyst Business Intelligence
Reporting Analyst - Optum Human Capital
Senior Business Analyst - CaseWare
Business Analyst II
Senior Strategic Business Analyst SC -Target Team
Financial Analyst
Business Analyst Intern - Safco
Sr Business Analyst
Senior Business Analyst
Sr Agile Business Analyst
Pricing Analyst
Business Intelligence (BI) Analyst/Operations Assistant
Sr ERP Business Analyst
Business Analyst - Brokerage Trade Reporting (St. Paul MN)
Business Analyst Senior Telehealth
Sr. Business Analyst
INFORMATIC SENIOR DATA ANALYST
IT Business Analyst Intern
Business Intelligence Intern
SWIFT Functional Business Analyst - State Prog Admin Sr
Sr. Insights & Reporting Analyst - Multiple locations
Senior Business Analyst
Sales and Operations Analyst II
Oracle Business Analyst Team Lead Oracle eBS
Sr. Business Analyst
Sr Analyst IT Functional Applications
SAP Procure to Pay Senior Business Analyst
Business Analyst Sr Job
Sr. IT Business Analyst
Sr. Technical Business Analyst
IT ServiceNow Business Analyst
Service Business Operations Analyst
Digital & Information Services Intern – Data Science Summer 2020
U.S. Bank Commercial Loan Legal Project Analyst - Minneapolis MN
IT - Data and Software Development Intern
Business Analyst IV - Business Transformation Office (BTO) *Multiple Openings
Sales Operations Analyst
Sr Contract Analyst
Sales Operations Automation Analyst (Salesforce.com)
Senior Business Analyst
Client Services Senior Analyst
Senior Programmer Analyst/Database Designer
Senior Marketing Analyst- Email and Mobile Communications
Business Analyst Manager - Minneapolis MN
Senior Technical Business Analyst
Business Technical Analyst
BA
Sr Business Analyst
Sr Business Analyst
Hybris Business Analyst
Procurement Analyst
Senior Healthcare Economics Analyst
Business Analysis
Sr. Business Intelligence Analyst
Sr. Business Analyst-Clinical
Sr. ERP Business Analyst
Lead IT Business Process Analyst - APO
SAP Business Objects Administrator
IT Business Analyst Intern
Sr Business Analyst Corporate Security
Senior Salesforce Business Analyst
Technology Business Analyst (EDI)
Senior Budget and Evaluation Analyst
Director Data Analytics - Supply Chain
Technical Business Analyst (Salesforce)
Senior Business Analyst
IT Business Analyst Senior
Project Analyst 4 - Portfolio Operational Specialist (Minneapolis MN)
Associate Supply Chain Analyst
Corporate Sales Analyst - Cloud Integration Software
SAP Business Analyst for Source to Pay (STP)
Analytic Consultant 4 - Conduct Analytics
Principal IT Business Systems Analyst - Salesforce.com
Business Analyst Sr - SAP
Analytic Consultant 4
Financial Analyst – Broker Dealer
Sr. Strategic Operations Analyst
Lead F&B Supply Chain Analyst- Transportation
Sr. Analyst Sales Operations
Director of Business Intelligence
Senior Business Analyst-Identity & Access Management (IAM)
Senior Data Analytics Manager - Payments - Minneapolis MN
Sales Operations Strategic Analyst Cardiac and Vascular Group - Mounds View MN
Sr. ERP Business Analyst
Sr. Pricing Analyst
Sr. Business Process Analyst
Senior Business Analyst
SAP APO Solution Manager (DP/SNP/GATP)
IDeaS Sr. Finance Analyst
Senior Sales Operations Analyst - Structural Heart Valves
Business Analyst III - Business Transformation Office (BTO)
Director - Audit Data Analytics
Sr Business Process Analyst - Policyholder Services
MSP - Business Alignment (BA)
BA
Financial Analyst – Broker Dealer
Analytics Consultant (SQL/SAS)
Sr. Pricing Analyst
Business Intelligence Advisor
Sr. BA - Healthcare
Senior Claims Business Process Analyst
BA Contract - MicroStrategy
Sr Healthcare Econ Analyst (SAS)
Sr. Pricing Analyst
Senior Software Business Analyst
Sr. ERP Business Analyst
Senior Technical Business Analyst
Financial Director - Enterprise Business Intelligence (EBI)
Lead F&B Supply Chain Analyst
Senior Business Analyst-Pricing and Contracts- PI
Senior Financial Analyst
Senior Manager Business Intelligence
Product Knowledge Manager – Business Intelligence & Reporting
Sales Operations Analyst - Salesforce.com Administrator
Retail IT BA
Business Objects Administrator – Business Objects 4.2 Upgrade Implementation Tableau SQL
Business Intelligence Manager
Senior Business Analysis Consultant
SAP BA Finance
Sr. Financial Analyst
Analytic Consultant 4 / CX Analytics
Senior Vendor Info Security Analyst
Agile Process Analytics Consultant
Multi-Channel Attribution Consultant (Analytic Consultant 5)
Senior Salesforce Technical Business Analyst
Senior Salesforce Business Analyst
Business Intelligence Architect/Manager
Financial Analyst 2 – Customer Success
Senior Manager Operational Risk and Data Analytics
Product Owner / Sr. Business Process Analyst - Routing and Ancillary
Senior Business Analyst Software Development
Senior Lead IT Business Process Analyst
Analytic Consultant 4 - Consumer Lending Analytics Consultant
Salesforce Sr. Business Analyst
IT Infrastructure BA
Sr Info Security Analyst - SOX IT Controls
Cloud Analytics Consultant - AC4
Project Manager - DataWareHousing / Business Intelligence
Business Analyst
Senior Manager Operational Risk and Data Analytics
Product Owner / Sr. Business Process Analyst - Routing and Ancillary
Senior Business Analyst Software Development
Senior Lead IT Business Process Analyst
Analytic Consultant 4 - Consumer Lending Analytics Consultant
Salesforce Sr. Business Analyst
IT Infrastructure BA
Sr Info Security Analyst - SOX IT Controls
Cloud Analytics Consultant - AC4
Project Manager - DataWareHousing / Business Intelligence
Business Analyst
Senior Manager Operational Risk and Data Analytics
Product Owner / Sr. Business Process Analyst - Routing and Ancillary
Senior Business Analyst Software Development
Senior Lead IT Business Process Analyst
Analytic Consultant 4 - Consumer Lending Analytics Consultant
Salesforce Sr. Business Analyst
IT Infrastructure BA
Sr Info Security Analyst - SOX IT Controls
Cloud Analytics Consultant - AC4
Project Manager - DataWareHousing / Business Intelligence
Business Analyst
Senior Manager Operational Risk and Data Analytics
Product Owner / Sr. Business Process Analyst - Routing and Ancillary
Senior Business Analyst Software Development
Senior Lead IT Business Process Analyst
Analytic Consultant 4 - Consumer Lending Analytics Consultant
Salesforce Sr. Business Analyst
IT Infrastructure BA
Sr Info Security Analyst - SOX IT Controls
Cloud Analytics Consultant - AC4
Project Manager - DataWareHousing / Business Intelligence
Business Analyst
Senior Manager Operational Risk and Data Analytics
Product Owner / Sr. Business Process Analyst - Routing and Ancillary
Senior Business Analyst Software Development
Senior Lead IT Business Process Analyst
Analytic Consultant 4 - Consumer Lending Analytics Consultant
Salesforce Sr. Business Analyst
IT Infrastructure BA
Sr Info Security Analyst - SOX IT Controls
Cloud Analytics Consultant - AC4
Project Manager - DataWareHousing / Business Intelligence
Business Analyst
Senior Manager Operational Risk and Data Analytics
Product Owner / Sr. Business Process Analyst - Routing and Ancillary
Senior Business Analyst Software Development
Senior Lead IT Business Process Analyst
Analytic Consultant 4 - Consumer Lending Analytics Consultant
Salesforce Sr. Business Analyst
IT Infrastructure BA
Sr Info Security Analyst - SOX IT Controls
Cloud Analytics Consultant - AC4
Project Manager - DataWareHousing / Business Intelligence
Business Analyst
Senior Manager Operational Risk and Data Analytics
Product Owner / Sr. Business Process Analyst - Routing and Ancillary
Senior Business Analyst Software Development
Senior Lead IT Business Process Analyst
Analytic Consultant 4 - Consumer Lending Analytics Consultant
Salesforce Sr. Business Analyst
IT Infrastructure BA
Sr Info Security Analyst - SOX IT Controls
Cloud Analytics Consultant - AC4
Project Manager - DataWareHousing / Business Intelligence
Business Analyst
Senior Manager Operational Risk and Data Analytics
Product Owner / Sr. Business Process Analyst - Routing and Ancillary
Senior Business Analyst Software Development
Senior Lead IT Business Process Analyst
Analytic Consultant 4 - Consumer Lending Analytics Consultant
Salesforce Sr. Business Analyst
IT Infrastructure BA
Sr Info Security Analyst - SOX IT Controls
Cloud Analytics Consultant - AC4
Project Manager - DataWareHousing / Business Intelligence
Business Analyst
Senior Manager Operational Risk and Data Analytics
Product Owner / Sr. Business Process Analyst - Routing and Ancillary
Senior Business Analyst Software Development
Senior Lead IT Business Process Analyst
Analytic Consultant 4 - Consumer Lending Analytics Consultant
Salesforce Sr. Business Analyst
IT Infrastructure BA
Sr Info Security Analyst - SOX IT Controls
Cloud Analytics Consultant - AC4
Project Manager - DataWareHousing / Business Intelligence
Business Analyst
Senior Manager Operational Risk and Data Analytics
Product Owner / Sr. Business Process Analyst - Routing and Ancillary
Senior Business Analyst Software Development
Senior Lead IT Business Process Analyst
Analytic Consultant 4 - Consumer Lending Analytics Consultant
Salesforce Sr. Business Analyst
IT Infrastructure BA
Sr Info Security Analyst - SOX IT Controls
Cloud Analytics Consultant - AC4
Project Manager - DataWareHousing / Business Intelligence
Business Analyst
Senior Manager Operational Risk and Data Analytics
Product Owner / Sr. Business Process Analyst - Routing and Ancillary
Senior Business Analyst Software Development
Senior Lead IT Business Process Analyst
Analytic Consultant 4 - Consumer Lending Analytics Consultant
Salesforce Sr. Business Analyst
IT Infrastructure BA
Sr Info Security Analyst - SOX IT Controls
Cloud Analytics Consultant - AC4
Project Manager - DataWareHousing / Business Intelligence
Business Analyst
Senior Manager Operational Risk and Data Analytics
Product Owner / Sr. Business Process Analyst - Routing and Ancillary
Senior Business Analyst Software Development
Senior Lead IT Business Process Analyst
Analytic Consultant 4 - Consumer Lending Analytics Consultant
Salesforce Sr. Business Analyst
IT Infrastructure BA
Sr Info Security Analyst - SOX IT Controls
Cloud Analytics Consultant - AC4
Project Manager - DataWareHousing / Business Intelligence
Business Analyst
Senior Manager Operational Risk and Data Analytics
Product Owner / Sr. Business Process Analyst - Routing and Ancillary
Senior Business Analyst Software Development
Senior Lead IT Business Process Analyst
Analytic Consultant 4 - Consumer Lending Analytics Consultant
Salesforce Sr. Business Analyst
IT Infrastructure BA
Sr Info Security Analyst - SOX IT Controls
Cloud Analytics Consultant - AC4
Project Manager - DataWareHousing / Business Intelligence
Business Analyst
Senior Manager Operational Risk and Data Analytics
Product Owner / Sr. Business Process Analyst - Routing and Ancillary
Senior Business Analyst Software Development
Senior Lead IT Business Process Analyst
Analytic Consultant 4 - Consumer Lending Analytics Consultant
Salesforce Sr. Business Analyst
IT Infrastructure BA
Sr Info Security Analyst - SOX IT Controls
Cloud Analytics Consultant - AC4
Project Manager - DataWareHousing / Business Intelligence
Business Analyst
Senior Manager Operational Risk and Data Analytics
Product Owner / Sr. Business Process Analyst - Routing and Ancillary
Senior Business Analyst Software Development
Senior Lead IT Business Process Analyst
Analytic Consultant 4 - Consumer Lending Analytics Consultant
Salesforce Sr. Business Analyst
IT Infrastructure BA
Sr Info Security Analyst - SOX IT Controls
Cloud Analytics Consultant - AC4
Project Manager - DataWareHousing / Business Intelligence
Business Analyst
Data Scientist
Data Scientist
Data Scientist - Nationwide Opportunities
Data Scientist
Data Scientist
Data Scientist (Maplewood MN)
Data Scientist
Data Scientist
Data Scientist II
Data Scientist
Quality Data Reviewer/Scientist
Data Scientist
Data Scientist
Data Scientist - Nationwide Opportunities
Data Scientist
Data Scientist
Data Scientist (Maplewood MN)
Data Scientist
Data Scientist
Data Scientist II
Data Scientist
Quality Data Reviewer/Scientist
Quality Data Reviewer/Scientist
Data Scientist/Sr. Scientific Programmer (Researcher 6)
Data Scientist
Senior Data Scientist
Healthcare Data Scientist
Data Scientist - Richfield MN
Data Scientist 2
Senior Data Scientist
Data Scientist
Senior Data Scientist
Sr. Data Scientist
Sr. Data Scientist
Sr. Data Scientist
Sr. Data Scientist Forecasting
Intern - Data Science
Lead Data Scientist - Testing COE

In [0]:
#open csv with pandas
import pandas as pd
simplyhiredjobs = pd.read_csv('/content/drive/My Drive/jobs_indeed.csv')

In [27]:
simplyhiredjobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3821 entries, 0 to 3820
Data columns (total 6 columns):
Data Analyst                                                                                                                                                        3821 non-null object
Enable Data                                                                                                                                                         3821 non-null object
Minneapolis MN                                                                                                                                                      3821 non-null object
A data analyst primarily works with data in a given system performing analysis on those data sets. Analysts help data engineers and scientists in understanding…    3821 non-null object
Estimated: $77000 - $97000 a year                                                                                                                                   3821 non-null object
https://www.simplyhired.com/job/J2pPaBAhYuNvoTKIZgqXuW4W7Us8YPwSVSvCX0Ek9QnfG8CIVK-4ug?q=data+analyst                                                               3821 non-null object
dtypes: object(6)
memory usage: 179.2+ KB

In [0]:
#change the columns 
simplyhiredjobs.columns = ['Title','Business','Location','Description','Salary','Link']
simplyhiredjobs['Salary']

In [29]:
#scrape the numbers from salary after the dollar sign
salaries = []
temp = []
temp_letters = None
for i,salary in enumerate(simplyhiredjobs['Salary']):
  for j,letter in enumerate(salary):
    if letter == '$':
      temp.append(str(salary[j+1:j+7]).strip())
  salaries.append(temp)
  temp = []
salaries

[['38000', '49000'],
 ['61000', '85000'],
 ['43000', '60000'],
 ['72000', '92000'],
 ['60000', '80000'],
 ['40000', '54000'],
 ['52000', '74000'],
 ['64000', '91000'],
 ['50000', '74000'],
 ['52000', '66000'],
 ['77000', '97000'],
 ['38000', '49000'],
 ['61000', '85000'],
 ['43000', '60000'],
 ['72000', '92000'],
 ['60000', '80000'],
 ['40000', '54000'],
 ['52000', '74000'],
 ['64000', '91000'],
 ['50000', '74000'],
 ['52000', '66000'],
 ['73000', '96000'],
 ['61000', '80000'],
 ['67000', '92000'],
 ['68000', '96000'],
 ['48000', '65000'],
 ['23 - $', '34 an'],
 ['72000', '92000'],
 ['60000', '84000'],
 ['72000', '98000'],
 ['77000', '96000'],
 ['97000', '120000'],
 ['62000', '81000'],
 ['68000', '96000'],
 ['54000', '71000'],
 [],
 ['31 - $', '43 an'],
 ['49000', '71000'],
 ['80000', '100000'],
 ['67000', '88000'],
 ['78000', '110000'],
 ['72000', '90000'],
 [],
 ['61000', '79000'],
 ['75000', '95000'],
 ['92000', '130000'],
 ['45000', '63000'],
 ['75000', '94000'],
 ['37 - $', '45 an'],
 ['66000', '89000'],
 ['67000', '87000'],
 ['42000', '59000'],
 ['97000', '130000'],
 ['46 an'],
 ['54000', '68000'],
 ['80000', '110000'],
 ['83000', '110000'],
 ['62000', '86000'],
 ['90000', '120000'],
 ['74000', '100000'],
 ['40000', '55000'],
 ['40 - $', '90 an'],
 ['79000', '100000'],
 ['71000', '93000'],
 ['49000', '67000'],
 ['70000', '97000'],
 ['32 - $', '150 an'],
 ['75000', '95000'],
 ['73000', '100000'],
 ['83000', '110000'],
 ['44000', '62000'],
 ['85000', '120000'],
 ['69000', '98000'],
 ['62000', '85000'],
 ['62000', '85000'],
 ['120000', '140000'],
 ['77000', '110000'],
 ['74000', '100000'],
 ['66000', '87000'],
 ['61000', '84000'],
 ['52000', '71000'],
 ['92000', '130000'],
 ['28 - $', '30 an'],
 ['53000', '70000'],
 ['68000', '96000'],
 ['75000', '96000'],
 ['61000', '81000'],
 ['67000', '96000'],
 ['78000', '110000'],
 ['77000', '100000'],
 ['72000', '100000'],
 ['75000', '100000'],
 ['59000', '81000'],
 ['61000', '80000'],
 ['85000', '120000'],
 ['63000', '84000'],
 ['63000', '82000'],
 ['50000', '63000'],
 ['70000', '96000'],
 ['62000', '87000'],
 ['68000', '94000'],
 ['65000', '84000'],
 ['66000', '94000'],
 ['69000', '100000'],
 ['78000', '110000'],
 ['79000', '100000'],
 ['58000', '78000'],
 ['73000', '100000'],
 ['61000', '81000'],
 ['76000', '110000'],
 ['38000', '49000'],
 ['76000', '110000'],
 ['46000', '59000'],
 ['77000', '110000'],
 ['91000', '120000'],
 ['70000', '94000'],
 ['72000', '91000'],
 ['82000', '110000'],
 ['100000', '130000'],
 [],
 ['75000', '100000'],
 ['71000', '93000'],
 ['58000', '78000'],
 ['86000', '120000'],
 ['72000', '99000'],
 ['63000', '82000'],
 ['69000', '94000'],
 ['70000', '97000'],
 ['30000', '38000'],
 ['120000', '160000'],
 ['90000', '110000'],
 ['57000', '75000'],
 ['58000', '78000'],
 ['130000', '170000'],
 ['21 an'],
 ['60000', '82000'],
 ['73000', '95000'],
 ['68000', '88000'],
 ['75000', '97000'],
 ['63000', '91000'],
 ['75000', '110000'],
 ['62000', '90000'],
 ['86000', '120000'],
 ['67000', '95000'],
 ['73000', '110000'],
 ['79000', '110000'],
 ['72000', '99000'],
 ['77000', '100000'],
 ['70000', '91000'],
 ['41000', '57000'],
 ['74000', '110000'],
 ['58000', '79000'],
 ['69000', '97000'],
 ['49000', '68000'],
 ['75000', '100000'],
 ['60000', '89000'],
 ['56000', '74000'],
 ['71000', '100000'],
 ['84000', '110000'],
 ['100000', '140000'],
 ['58000', '79000'],
 ['61000', '79000'],
 ['69000', '99000'],
 ['67000', '90000'],
 ['77000', '97000'],
 ['90000', '120000'],
 ['47000', '66000'],
 ['68000', '100000'],
 ['73000', '94000'],
 ['50000', '67000'],
 ['70000', '96000'],
 ['72000', '100000'],
 ['71000', '99000'],
 ['62000', '92000'],
 ['32 - $', '44 an'],
 ['82000', '110000'],
 ['21 an'],
 ['68000', '91000'],
 ['75000', '110000'],
 ['84000', '110000'],
 ['53000', '70000'],
 ['50000', '70000'],
 ['77000', '100000'],
 ['78000', '110000'],
 ['42000', '57000'],
 ['68000', '98000'],
 ['31 - $', '51 an'],
 ['85000', '110000'],
 ['77000', '100000'],
 ['65000', '85000'],
 ['73000', '94000'],
 ['89000', '130000'],
 ['67000', '91000'],
 ['73000', '96000'],
 ['55000', '80000'],
 ['62000', '85000'],
 ['40000', '55000'],
 ['68000', '91000'],
 ['100000', '140000'],
 ['78000', '100000'],
 ['76000', '100000'],
 ['58000', '78000'],
 ['62000', '87000'],
 [],
 ['77000', '100000'],
 ['64000', '84000'],
 ['44000', '57000'],
 ['94000', '120000'],
 ['42000', '58000'],
 ['45000', '55000'],
 ['81000', '110000'],
 ['97000', '130000'],
 ['110000', '150000'],
 ['56000', '81000'],
 ['75000', '85000'],
 ['80000', '110000'],
 ['69000', '96000'],
 ['46000', '61000'],
 ['72000', '97000'],
 ['63000', '92000'],
 ['86000', '110000'],
 ['51000', '65000'],
 ['63000', '86000'],
 ['70000', '95000'],
 ['100000', '130000'],
 ['61000', '83000'],
 ['84000', '120000'],
 ['81000', '110000'],
 ['67000', '91000'],
 ['93000', '130000'],
 ['72000', '100000'],
 ['56 an'],
 ['76000', '100000'],
 ['61000', '88000'],
 ['48000', '63000'],
 [],
 ['47000', '61000'],
 ['44000', '58000'],
 ['69000', '97000'],
 ['79000', '110000'],
 ['100000', '130000'],
 ['66000', '92000'],
 ['35000', '49000'],
 ['76000', '100000'],
 ['83000', '110000'],
 ['66000', '82000'],
 ['77000', '100000'],
 ['73000', '100000'],
 ['74000', '95000'],
 ['81000', '110000'],
 ['72000', '93000'],
 ['79000', '100000'],
 ['65000', '85000'],
 ['93000', '130000'],
 [],
 ['95000', '120000'],
 ['56000', '72000'],
 ['36000', '51000'],
 ['78000', '110000'],
 ['72000', '92000'],
 ['75000', '100000'],
 ['49000', '66000'],
 [],
 ['93000', '120000'],
 ['55000', '78000'],
 ['58000', '83000'],
 ['80000', '110000'],
 ['78000', '110000'],
 ['51000', '67000'],
 ['54000', '75000'],
 ['23 - $', '34 an'],
 ['82000', '110000'],
 ['78000', '110000'],
 ['55000', '71000'],
 ['84000', '120000'],
 ['80000', '100000'],
 ['68000', '89000'],
 ['94000', '130000'],
 ['76000', '100000'],
 ['78000', '110000'],
 ['89000', '130000'],
 ['78000', '100000'],
 ['59000', '86000'],
 ['51000', '67000'],
 ['55000', '76000'],
 ['51000', '69000'],
 ['75000', '98000'],
 ['60000', '82000'],
 ['54000', '73000'],
 ['81000', '110000'],
 ['83000', '110000'],
 ['70000', '97000'],
 ['85000', '120000'],
 ['68000', '90000'],
 ['79000', '110000'],
 ['62000', '91000'],
 ['56000', '75000'],
 ['71000', '100000'],
 ['80000', '100000'],
 ['79000', '110000'],
 ['87000', '120000'],
 ['61000', '87000'],
 ['65000', '91000'],
 ['100000', '140000'],
 ['77000', '98000'],
 ['74000', '110000'],
 ['92000', '120000'],
 ['71000', '100000'],
 ['60 - $', '70 an'],
 ['39000', '51000'],
 ['80000', '100000'],
 ['100000', '150000'],
 ['68000', '96000'],
 ['76000', '97000'],
 ['95000', '130000'],
 ['76000', '110000'],
 ['63000', '90000'],
 ['76000', '100000'],
 ['53000', '75000'],
 ['52000', '66000'],
 ['73000', '99000'],
 ['58000', '82000'],
 ['96000', '130000'],
 ['84000', '110000'],
 ['95000', '120000'],
 ['95000', '130000'],
 ['66000', '94000'],
 ['76000', '96000'],
 ['80000', '100000'],
 ['63000', '84000'],
 ['100000', '140000'],
 ['100000', '130000'],
 ['130000', '180000'],
 ['59000', '77000'],
 ['66000', '92000'],
 ['56000', '72000'],
 ['84000', '110000'],
 [],
 ['75 - $', '85 an'],
 ['72000', '100000'],
 ['79000', '100000'],
 ['67000', '97000'],
 [],
 ['87000', '120000'],
 ['79000', '110000'],
 ['58000', '78000'],
 ['70000', '95000'],
 ['67000', '97000'],
 ['54000', '70000'],
 ['73000', '96000'],
 ['64000', '91000'],
 ['62000', '82000'],
 ['58000', '78000'],
 ['71000', '92000'],
 ['56000', '76000'],
 ['87000', '120000'],
 ['72000', '110000'],
 ['77000', '100000'],
 ['120000', '170000'],
 ['71000', '100000'],
 ['73000', '98000'],
 ['68000', '95000'],
 ['130000', '170000'],
 ['69000', '90000'],
 ['67000', '87000'],
 ['77000', '110000'],
 ['87000', '120000'],
 ['80000', '110000'],
 ['79000', '100000'],
 ['70000', '97000'],
 ['61000', '79000'],
 ['82000', '120000'],
 ['84000', '110000'],
 ['73000', '100000'],
 ['77000', '110000'],
 ['96000', '130000'],
 ['83000', '120000'],
 ['76000', '99000'],
 ['56000', '75000'],
 [],
 ['86000', '120000'],
 [],
 ['74000', '99000'],
 ['75000', '99000'],
 ['86000', '110000'],
 ['75000', '95000'],
 ['100000', '130000'],
 ['92000', '130000'],
 ['110000', '150000'],
 ['60000', '85000'],
 [],
 ['86000', '120000'],
 [],
 ['74000', '99000'],
 ['75000', '99000'],
 ['86000', '110000'],
 ['75000', '95000'],
 ['100000', '130000'],
 ['92000', '130000'],
 ['110000', '150000'],
 ['60000', '85000'],
 [],
 ['86000', '120000'],
 [],
 ['74000', '99000'],
 ['75000', '99000'],
 ['86000', '110000'],
 ['75000', '95000'],
 ['100000', '130000'],
 ['92000', '130000'],
 ['110000', '150000'],
 ['60000', '85000'],
 [],
 ['86000', '120000'],
 [],
 ['74000', '99000'],
 ['75000', '99000'],
 ['86000', '110000'],
 ['75000', '95000'],
 ['100000', '130000'],
 ['92000', '130000'],
 ['110000', '150000'],
 ['60000', '85000'],
 [],
 ['86000', '120000'],
 [],
 ['74000', '99000'],
 ['75000', '99000'],
 ['86000', '110000'],
 ['75000', '95000'],
 ['100000', '130000'],
 ['92000', '130000'],
 ['110000', '150000'],
 ['60000', '85000'],
 [],
 ['86000', '120000'],
 [],
 ['74000', '99000'],
 ['75000', '99000'],
 ['86000', '110000'],
 ['75000', '95000'],
 ['100000', '130000'],
 ['92000', '130000'],
 ['110000', '150000'],
 ['60000', '85000'],
 [],
 ['86000', '120000'],
 [],
 ['74000', '99000'],
 ['75000', '99000'],
 ['86000', '110000'],
 ['75000', '95000'],
 ['100000', '130000'],
 ['92000', '130000'],
 ['110000', '150000'],
 ['60000', '85000'],
 [],
 ['86000', '120000'],
 [],
 ['74000', '99000'],
 ['75000', '99000'],
 ['86000', '110000'],
 ['75000', '95000'],
 ['100000', '130000'],
 ['92000', '130000'],
 ['110000', '150000'],
 ['60000', '85000'],
 [],
 ['86000', '120000'],
 [],
 ['74000', '99000'],
 ['75000', '99000'],
 ['86000', '110000'],
 ['75000', '95000'],
 ['100000', '130000'],
 ['92000', '130000'],
 ['110000', '150000'],
 ['60000', '85000'],
 [],
 ['86000', '120000'],
 [],
 ['74000', '99000'],
 ['75000', '99000'],
 ['86000', '110000'],
 ['75000', '95000'],
 ['100000', '130000'],
 ['92000', '130000'],
 ['110000', '150000'],
 ['60000', '85000'],
 [],
 ['86000', '120000'],
 [],
 ['74000', '99000'],
 ['75000', '99000'],
 ['86000', '110000'],
 ['75000', '95000'],
 ['100000', '130000'],
 ['92000', '130000'],
 ['110000', '150000'],
 ['60000', '85000'],
 [],
 ['86000', '120000'],
 [],
 ['74000', '99000'],
 ['75000', '99000'],
 ['86000', '110000'],
 ['75000', '95000'],
 ['100000', '130000'],
 ['92000', '130000'],
 ['110000', '150000'],
 ['60000', '85000'],
 [],
 ['86000', '120000'],
 [],
 ['74000', '99000'],
 ['75000', '99000'],
 ['86000', '110000'],
 ['75000', '95000'],
 ['100000', '130000'],
 ['92000', '130000'],
 ['110000', '150000'],
 ['60000', '85000'],
 [],
 ['86000', '120000'],
 [],
 ['74000', '99000'],
 ['75000', '99000'],
 ['86000', '110000'],
 ['75000', '95000'],
 ['100000', '130000'],
 ['92000', '130000'],
 ['110000', '150000'],
 ['60000', '85000'],
 [],
 ['86000', '120000'],
 [],
 ['74000', '99000'],
 ['75000', '99000'],
 ['86000', '110000'],
 ['75000', '95000'],
 ['100000', '130000'],
 ['92000', '130000'],
 ['110000', '150000'],
 ['60000', '85000'],
 ['100000', '130000'],
 ['110000', '150000'],
 ['110000', '140000'],
 ['100000', '140000'],
 ['99000', '130000'],
 ['97000', '120000'],
 ['64000', '87000'],
 ['95000', '120000'],
 ['99000', '140000'],
 ['90000', '120000'],
 ['81000', '110000'],
 ['100000', '130000'],
 ['110000', '150000'],
 ['110000', '140000'],
 ['100000', '140000'],
 ['99000', '130000'],
 ['97000', '120000'],
 ['64000', '87000'],
 ['95000', '120000'],
 ['99000', '140000'],
 ['90000', '120000'],
 ['81000', '110000'],
 ['78000', '110000'],
 ['88000', '120000'],
 ['74000', '100000'],
 ['99000', '130000'],
 ['100000', '140000'],
 ['84000', '120000'],
 ['74000', '110000'],
 ['73000', '100000'],
 ['99000', '130000'],
 ['100000', '130000'],
 ['66000', '96000'],
 ['140000', '180000'],
 ['90000', '120000'],
 ['76000', '97000'],
 ['52000', '71000'],
 ['88000', '110000'],
 ['100000', '140000'],
 ['70000', '96000'],
 ['82000', '120000'],
 ['82000', '110000'],
 ['68000', '94000'],
 ['68000', '96000'],
 ['90000', '120000'],
 ['140000', '180000'],
 ['100000', '140000'],
 ['72000', '98000'],
 ['97000', '130000'],
 ['110000', '140000'],
 ['110000', '160000'],
 ['37 - $', '45 an'],
 ['69000', '88000'],
 ['50000', '67000'],
 ['110000', '150000'],
 ['77000', '100000'],
 ['87000', '120000'],
 ['69000', '98000'],
 ['80000', '110000'],
 ['92000', '130000'],
 ['96000', '120000'],
 ['83000', '110000'],
 ['76000', '100000'],
 ['77000', '110000'],
 ['46 - $', '150 an'],
 ['76000', '100000'],
 ['100000', '140000'],
 ['100000', '140000'],
 ['74000', '100000'],
 ['97000', '130000'],
 ['110000', '140000'],
 ['62000', '85000'],
 ['46000', '61000'],
 ['77000', '110000'],
 ['52000', '75000'],
 ['51000', '67000'],
 ['89000', '120000'],
 ['110000', '150000'],
 ['87000', '120000'],
 ['38000', '49000'],
 ['100000', '140000'],
 ['100000', '130000'],
 ['86000', '120000'],
 ['100000', '140000'],
 ['91000', '120000'],
 ['69000', '100000'],
 ['79000', '110000'],
 ['43000', '58000'],
 ['63000', '82000'],
 ['100000', '130000'],
 ['93000', '120000'],
 ['120000', '160000'],
 ['52000', '70000'],
 ['94000', '130000'],
 ['110000', '150000'],
 ['91000', '120000'],
 ['140000', '190000'],
 ['84000', '110000'],
 ['87000', '120000'],
 ['100000', '140000'],
 ['47000', '68000'],
 ['85000', '120000'],
 ['120000', '170000'],
 ['120000', '170000'],
 ['82000', '110000'],
 ['88000', '110000'],
 [],
 ['23000', '32000'],
 ['100000', '140000'],
 ['120000', '160000'],
 ['78000', '110000'],
 ['67000', '96000'],
 ['130000', '170000'],
 ['130000', '190000'],
 ['85000', '110000'],
 ['96000', '130000'],
 ['130000', '170000'],
 ['91000', '120000'],
 ['75000', '97000'],
 ['69000', '91000'],
 ['130000', '180000'],
 ['86000', '120000'],
 ['100000', '140000'],
 ['89000', '110000'],
 ['79000', '110000'],
 ['89000', '120000'],
 ['88000', '120000'],
 ['110000', '150000'],
 ['71000', '90000'],
 ['110000', '140000'],
 ['100000', '150000'],
 ['92000', '130000'],
 ['100000', '140000'],
 ['110000', '150000'],
 ['72000', '98000'],
 ['95000', '120000'],
 ['93000', '130000'],
 ['100000', '140000'],
 ['100000', '130000'],
 ['110000', '150000'],
 ['110000', '140000'],
 ['100000', '150000'],
 ['92000', '130000'],
 ['100000', '140000'],
 ['110000', '150000'],
 ['72000', '98000'],
 ['95000', '120000'],
 ['93000', '130000'],
 ['100000', '140000'],
 ['100000', '130000'],
 ['110000', '150000'],
 ['110000', '140000'],
 ['100000', '150000'],
 ['92000', '130000'],
 ['100000', '140000'],
 ['110000', '150000'],
 ['72000', '98000'],
 ['95000', '120000'],
 ['93000', '130000'],
 ['100000', '140000'],
 ['100000', '130000'],
 ['110000', '150000'],
 ['110000', '140000'],
 ['100000', '150000'],
 ['92000', '130000'],
 ['100000', '140000'],
 ['110000', '150000'],
 ['72000', '98000'],
 ['95000', '120000'],
 ['93000', '130000'],
 ['100000', '140000'],
 ['100000', '130000'],
 ['110000', '150000'],
 ['110000', '140000'],
 ['100000', '150000'],
 ['92000', '130000'],
 ['100000', '140000'],
 ['110000', '150000'],
 ['72000', '98000'],
 ['95000', '120000'],
 ['93000', '130000'],
 ['100000', '140000'],
 ['100000', '130000'],
 ['110000', '150000'],
 ['110000', '140000'],
 ['100000', '150000'],
 ['92000', '130000'],
 ['100000', '140000'],
 ['110000', '150000'],
 ['72000', '98000'],
 ['95000', '120000'],
 ['93000', '130000'],
 ['100000', '140000'],
 ['100000', '130000'],
 ['110000', '150000'],
 ['110000', '140000'],
 ['100000', '150000'],
 ['92000', '130000'],
 ['100000', '140000'],
 ['110000', '150000'],
 ['72000', '98000'],
 ['95000', '120000'],
 ['93000', '130000'],
 ['100000', '140000'],
 ['100000', '130000'],
 ['110000', '150000'],
 ['110000', '140000'],
 ['100000', '150000'],
 ['92000', '130000'],
 ['100000', '140000'],
 ['110000', '150000'],
 ['72000', '98000'],
 ['95000', '120000'],
 ['93000', '130000'],
 ['100000', '140000'],
 ['100000', '130000'],
 ['110000', '150000'],
 ['110000', '140000'],
 ['100000', '150000'],
 ['92000', '130000'],
 ['100000', '140000'],
 ['110000', '150000'],
 ['72000', '98000'],
 ['95000', '120000'],
 ['93000', '130000'],
 ['100000', '140000'],
 ['100000', '130000'],
 ['110000', '150000'],
 ['110000', '140000'],
 ['100000', '150000'],
 ['92000', '130000'],
 ['100000', '140000'],
 ['110000', '150000'],
 ['72000', '98000'],
 ['95000', '120000'],
 ['93000', '130000'],
 ['100000', '140000'],
 ['100000', '130000'],
 ['110000', '150000'],
 ['110000', '140000'],
 ['100000', '150000'],
 ['92000', '130000'],
 ['100000', '140000'],
 ['110000', '150000'],
 ['72000', '98000'],
 ['95000', '120000'],
 ['93000', '130000'],
 ['100000', '140000'],
 ['100000', '130000'],
 ['110000', '150000'],
 ['110000', '140000'],
 ['100000', '150000'],
 ['92000', '130000'],
 ['100000', '140000'],
 ['110000', '150000'],
 ['72000', '98000'],
 ['95000', '120000'],
 ['93000', '130000'],
 ['100000', '140000'],
 ['100000', '130000'],
 ['110000', '150000'],
 ['110000', '140000'],
 ['100000', '150000'],
 ['92000', '130000'],
 ['100000', '140000'],
 ['110000', '150000'],
 ['72000', '98000'],
 ['95000', '120000'],
 ['93000', '130000'],
 ['100000', '140000'],
 ['100000', '130000'],
 ['110000', '150000'],
 ['110000', '140000'],
 ['100000', '150000'],
 ['92000', '130000'],
 ['100000', '140000'],
 ['110000', '150000'],
 ['72000', '98000'],
 ['95000', '120000'],
 ['93000', '130000'],
 ['100000', '140000'],
 ['100000', '130000'],
 ['110000', '150000'],
 ['110000', '140000'],
 ['100000', '150000'],
 ['92000', '130000'],
 ['100000', '140000'],
 ['110000', '150000'],
 ['72000', '98000'],
 ['95000', '120000'],
 ['93000', '130000'],
 ['100000', '140000'],
 ['100000', '130000'],
 ['110000', '150000'],
 ['110000', '140000'],
 ['100000', '150000'],
 ['92000', '130000'],
 ['100000', '140000'],
 ['110000', '150000'],
 ['72000', '98000'],
 ['95000', '120000'],
 ['93000', '130000'],
 ['100000', '140000'],
 ['100000', '130000'],
 ['110000', '150000'],
 ['110000', '140000'],
 ['100000', '150000'],
 ['92000', '130000'],
 ['100000', '140000'],
 ['110000', '150000'],
 ['72000', '98000'],
 ['95000', '120000'],
 ['93000', '130000'],
 ['100000', '140000'],
 ['100000', '130000'],
 ['110000', '150000'],
 ['110000', '140000'],
 ['100000', '150000'],
 ['92000', '130000'],
 ['100000', '140000'],
 ['110000', '150000'],
 ['72000', '98000'],
 ['95000', '120000'],
 ['93000', '130000'],
 ['100000', '140000'],
 ['100000', '130000'],
 ['110000', '150000'],
 ['110000', '140000'],
 ['100000', '150000'],
 ['92000', '130000'],
 ['100000', '140000'],
 ['110000', '150000'],
 ['72000', '98000'],
 ['95000', '120000'],
 ['93000', '130000'],
 ['100000', '140000'],
 ['100000', '130000'],
 ['110000', '150000'],
 ['110000', '140000'],
 ['100000', '150000'],
 ['92000', '130000'],
 ['100000', '140000'],
 ['110000', '150000'],
 ['72000', '98000'],
 ['95000', '120000'],
 ['93000', '130000'],
 ['100000', '140000'],
 ['100000', '130000'],
 ['110000', '150000'],
 ['110000', '140000'],
 ['100000', '150000'],
 ['92000', '130000'],
 ['100000', '140000'],
 ['110000', '150000'],
 ['72000', '98000'],
 ['95000', '120000'],
 ['93000', '130000'],
 ['100000', '140000'],
 ['100000', '130000'],
 ['110000', '150000'],
 ['110000', '140000'],
 ['100000', '150000'],
 ['92000', '130000'],
 ['100000', '140000'],
 ['110000', '150000'],
 ['72000', '98000'],
 ['95000', '120000'],
 ['93000', '130000'],
 ['100000', '140000'],
 ['100000', '130000'],
 ['110000', '150000'],
 ['110000', '140000'],
 ['100000', '150000'],
 ['92000', '130000'],
 ['100000', '140000'],
 ['110000', '150000'],
 ['72000', '98000'],
 ['95000', '120000'],
 ['93000', '130000'],
 ['100000', '140000'],
 ['100000', '130000'],
 ['110000', '150000'],
 ['110000', '140000'],
 ['100000', '150000'],
 ['92000', '130000'],
 ['100000', '140000'],
 ['110000', '150000'],
 ['72000', '98000'],
 ['95000', '120000'],
 ['93000', '130000'],
 ['100000', '140000'],
 ['100000', '130000'],
 ['110000', '150000'],
 ['110000', '140000'],
 ['100000', '150000'],
 ['92000', '130000'],
 ['100000', '140000'],
 ['110000', '150000'],
 ['72000', '98000'],
 ['95000', '120000'],

In [0]:
#turn to pandas dataframe
salar = pd.DataFrame(salaries)

In [31]:
#see how many numbers there are in each column. Any non numbers?
import numpy as np
salar.applymap(np.isreal).sum()
#salar[0][:5]
#salar[0].value_counts()

0    116
1    133
dtype: int64

In [0]:
#make new column and fill with numbers and coerce non numbers into nan
salar[2] = pd.to_numeric(salar[0],errors='coerce')

In [0]:
#make new column and fill with numbers and coerce non numbers into nan
salar[3] = pd.to_numeric(salar[1],errors='coerce')

In [0]:
#made a salary column by taking the middle of the ranges
salar['salary'] = (salar[2] + salar[3]) / 2

In [35]:
salar[0].str.isnumeric().value_counts()
#this many non formmated salaries let me see

True     3621
False      84
Name: 0, dtype: int64

In [36]:
#filter out salaries where isnumeric is False or 0 value
nonformat = pd.DataFrame(salaries)
nonformat = nonformat[nonformat[0].str.isnumeric() < 1]
nonformat

           0      1
26    23 - $  34 an
36    31 - $  43 an
48    37 - $  45 an
53     46 an   None
61    40 - $  90 an
...      ...    ...
2697  16 - $  17 an
2728  28 - $  30 an
2847  65 - $  85 an
3320  37 - $  45 an
3352  21 - $  23 an

[84 rows x 2 columns]

In [37]:
#the values not in ranges are dollars per hour so I grab the first two numbers
#have to use the .str method to be able to get a portion of the cell
nonformat[2] = nonformat[0].str[:2]
nonformat

           0      1   2
26    23 - $  34 an  23
36    31 - $  43 an  31
48    37 - $  45 an  37
53     46 an   None  46
61    40 - $  90 an  40
...      ...    ...  ..
2697  16 - $  17 an  16
2728  28 - $  30 an  28
2847  65 - $  85 an  65
3320  37 - $  45 an  37
3352  21 - $  23 an  21

[84 rows x 3 columns]

In [38]:
nonformat[3] = nonformat[1].str[:2]
nonformat

           0      1   2     3
26    23 - $  34 an  23    34
36    31 - $  43 an  31    43
48    37 - $  45 an  37    45
53     46 an   None  46  None
61    40 - $  90 an  40    90
...      ...    ...  ..   ...
2697  16 - $  17 an  16    17
2728  28 - $  30 an  28    30
2847  65 - $  85 an  65    85
3320  37 - $  45 an  37    45
3352  21 - $  23 an  21    23

[84 rows x 4 columns]

In [39]:
#slightly out of order and using the same variable nonformat
#convert from string to integers
nonformat[2] = nonformat[2].astype(int)
#turn any na's into 0's ( the hourlies that do not have hourly ranges so there is no second column value but there is first column value)
nonformat[3] = nonformat[3].fillna(value=0)
#turn the strings to integers
nonformat[3] = nonformat[3].astype(int)
#combine hourly ranges into averages
nonformat[4] = (nonformat[2] + nonformat[3])/ 2
nonformat

           0      1   2   3     4
26    23 - $  34 an  23  34  28.5
36    31 - $  43 an  31  43  37.0
48    37 - $  45 an  37  45  41.0
53     46 an   None  46   0  23.0
61    40 - $  90 an  40  90  65.0
...      ...    ...  ..  ..   ...
2697  16 - $  17 an  16  17  16.5
2728  28 - $  30 an  28  30  29.0
2847  65 - $  85 an  65  85  75.0
3320  37 - $  45 an  37  45  41.0
3352  21 - $  23 an  21  23  22.0

[84 rows x 5 columns]

In [0]:
#query where hourlies are not in a hourly range or 0 when using is numeric function
nonrangehourly = nonformat[nonformat[3] == 0]

In [0]:
#pointless join-was going to try to use np.where but can't with join or merge
nonformat =nonrangehourly.join(nonformat,how='outer',lsuffix='j')

In [0]:
#new column that either takes the value from column with the averaged hourly or the single hourly based on if there was a zero value in the non numeric second hourly column
nonformat['5'] = nonformat.apply(lambda x: x['2'] if( x['3'] == 0) else x['4'] , axis=1)

In [43]:
#not sure what this is
nonformat[nonformat['5'] > 0]

         0j    1j    2j   3j    4j       0      1   2   3     4     5
26      NaN   NaN   NaN  NaN   NaN  23 - $  34 an  23  34  28.5  28.5
36      NaN   NaN   NaN  NaN   NaN  31 - $  43 an  31  43  37.0  37.0
48      NaN   NaN   NaN  NaN   NaN  37 - $  45 an  37  45  41.0  41.0
53    46 an  None  46.0  0.0  23.0   46 an   None  46   0  23.0  46.0
61      NaN   NaN   NaN  NaN   NaN  40 - $  90 an  40  90  65.0  65.0
...     ...   ...   ...  ...   ...     ...    ...  ..  ..   ...   ...
2697    NaN   NaN   NaN  NaN   NaN  16 - $  17 an  16  17  16.5  16.5
2728    NaN   NaN   NaN  NaN   NaN  28 - $  30 an  28  30  29.0  29.0
2847    NaN   NaN   NaN  NaN   NaN  65 - $  85 an  65  85  75.0  75.0
3320    NaN   NaN   NaN  NaN   NaN  37 - $  45 an  37  45  41.0  41.0
3352    NaN   NaN   NaN  NaN   NaN  21 - $  23 an  21  23  22.0  22.0

[84 rows x 11 columns]

In [0]:
#this didn't do what I wanted it to do
salar['isna'] = salar[0].isna()

In [45]:
#this also didn't do what I thought it would do
salar[salar['isna'] == True][1].value_counts()

Series([], Name: 1, dtype: int64)

In [0]:
#add a formatted hourly to the salar database which is the one with the salary ranges- convert hourly to salary
#this automatically puts them together based on the indexes and the rest NaN
salar['formatted'] = nonformat['5'] *2000

In [0]:
#make a new column and fill it depending on if there is a hourly or a salary based on if there are Nan in formatted or not
salar['combined'] = salar.apply(lambda x: x['salary'] if(np.isnan(x['formatted']) == True) else x['formatted'] , axis=1)

In [48]:
salar

           0       1         2         3    salary   isna  formatted  combined
0      38000   49000   38000.0   49000.0   43500.0  False        NaN   43500.0
1      61000   85000   61000.0   85000.0   73000.0  False        NaN   73000.0
2      43000   60000   43000.0   60000.0   51500.0  False        NaN   51500.0
3      72000   92000   72000.0   92000.0   82000.0  False        NaN   82000.0
4      60000   80000   60000.0   80000.0   70000.0  False        NaN   70000.0
...      ...     ...       ...       ...       ...    ...        ...       ...
3816   83000  120000   83000.0  120000.0  101500.0  False        NaN  101500.0
3817  110000  140000  110000.0  140000.0  125000.0  False        NaN  125000.0
3818  120000  160000  120000.0  160000.0  140000.0  False        NaN  140000.0
3819  100000  140000  100000.0  140000.0  120000.0  False        NaN  120000.0
3820   93000  130000   93000.0  130000.0  111500.0  False        NaN  111500.0

[3821 rows x 8 columns]

In [49]:
simplyhiredjobs

                                                  Title  ...                                               Link
0                                 Capstone Data Analyst  ...  https://www.simplyhired.com/job/czVsuret4T5p1D...
1                                Marketing Data Analyst  ...  https://www.simplyhired.com/job/o8-Yl-jOOsIrl7...
2                                      Jr. Data Analyst  ...  https://www.simplyhired.com/job/OZzt9r2LshBjzn...
3                           Pharmaceutical Data Analyst  ...  https://www.simplyhired.com/job/tmS82BNKF2LTka...
4                               Junior Business Analyst  ...  https://www.simplyhired.com/job/a1sFvZCMBsmt7u...
...                                                 ...  ...                                                ...
3816  Manager Quality Assurance – SAP & Deltek Costp...  ...  https://www.simplyhired.com/job/U63ZRZe6nIhl4Q...
3817  Senior Principal IT Architect - IMS MDM Archit...  ...  https://www.simplyhired.com/job/n8jxh2UNclVvaf...
3818  Principal IT Architect - IMS Cloud Data Archit...  ...  https://www.simplyhired.com/job/ElX_32QIcn5wHD...
3819  Artificial Intelligence Senior Manager - Appli...  ...  https://www.simplyhired.com/job/JefMitiEO7WBnN...
3820  Artificial Intelligence Senior Consultant - Ap...  ...  https://www.simplyhired.com/job/grnekcs6fuU8vA...

[3821 rows x 6 columns]

In [0]:
#add the proper salary values into the main database salary column
simplyhiredjobs['Salary'] = salar['combined']

In [51]:
simplyhiredjobs

                                                  Title  ...                                               Link
0                                 Capstone Data Analyst  ...  https://www.simplyhired.com/job/czVsuret4T5p1D...
1                                Marketing Data Analyst  ...  https://www.simplyhired.com/job/o8-Yl-jOOsIrl7...
2                                      Jr. Data Analyst  ...  https://www.simplyhired.com/job/OZzt9r2LshBjzn...
3                           Pharmaceutical Data Analyst  ...  https://www.simplyhired.com/job/tmS82BNKF2LTka...
4                               Junior Business Analyst  ...  https://www.simplyhired.com/job/a1sFvZCMBsmt7u...
...                                                 ...  ...                                                ...
3816  Manager Quality Assurance – SAP & Deltek Costp...  ...  https://www.simplyhired.com/job/U63ZRZe6nIhl4Q...
3817  Senior Principal IT Architect - IMS MDM Archit...  ...  https://www.simplyhired.com/job/n8jxh2UNclVvaf...
3818  Principal IT Architect - IMS Cloud Data Archit...  ...  https://www.simplyhired.com/job/ElX_32QIcn5wHD...
3819  Artificial Intelligence Senior Manager - Appli...  ...  https://www.simplyhired.com/job/JefMitiEO7WBnN...
3820  Artificial Intelligence Senior Consultant - Ap...  ...  https://www.simplyhired.com/job/grnekcs6fuU8vA...

[3821 rows x 6 columns]

In [0]:
#I thought there would be duplicates so I dropped duplicates
simplyhiredjobs.drop_duplicates(subset=None, keep='first', inplace=True)

In [55]:
simplyhiredjobs.describe() #got rid of hourly properly lowest is 27500

              Salary
count    2278.000000
mean    87065.847234
std     23263.084757
min     27500.000000
25%     72000.000000
50%     85500.000000
75%    102000.000000
max    200000.000000

In [0]:
#get all the full job descriptions for text processing
#full_descriptions = pd.DataFrame()
full_descript = []
temp_descript = []
jobs_url = simplyhiredjobs.iloc[0,5]
#print(jobs_url)
for link in simplyhiredjobs['Link']:
  uClient = uReq(link)
  page_html = uClient.read()
  uClient.close()

        #html parsing
  page_soup = soup(page_html, "html.parser")

        #grab all divs with a class of result
  results = page_soup.find('div',{'class':'viewjob-description'})
  #results = results.findAll("li")
  #print(len(results))
  #print(results.text)
  print(link)
  try:
    for result in results:
      temp_descript.append(result.text)
    full_descript.append(temp_descript)
    temp_descript = []
  except:
    full_descript.append(results.text)
full_descriptions = pd.DataFrame(full_descript)
full_descriptions

For some reason that I couldn't figure out the object that bs4 got was a nonetype even though it has content so it isn't a nonetype but a bs4.element.tag or something of a bs4 type. I have been getting some times where it is a nonetype and then sometimes the same code on the same website is not a nonetype. Maybe the simplyhired website doesn't want scrapers so they do some stealthy anti scraping website technology on my ip address.

In [85]:
jobs_url = 'https://www.simplyhired.com/job/uv19x3ZjZqUZa-b1EIKWftcjhNjqF8XlaHgmeoD3UzVO5tYLShKSsQ?q=data+analyst'
jobs_url
uClient = uReq(jobs_url)
page_html = uClient.read()
uClient.close()
page_soup = soup(page_html, "html.parser")
results = page_soup.find('div',{'class':'viewjob-description'})
  #results = results.findAll("li")
print(type(results))
print(results.text)

<class 'bs4.element.Tag'>
Job SummaryHiHope you are doing good.Below is the urgent need by the client. Please do take a look and let me know your interest for the same.**Position: PLM Data AnalystLocation: Saint Paul, MNContractMandatory Skills: Minimum 2 -4 years of experience in support or end-user software support demonstrating software troubleshooting skillsStrong experience in Microsoft Office in specific to MS Word and ExcelStrong written and verbal communication skills needed for documentation, e-mail, and announcementsData correction, Data cleansing**Job Roles/Responsibilities: Work closely with customers to understand their business process and provide them best solution.Strong troubleshooting and problem-solving skills with the ability to handle multiple tasksExcellent organizational, communication and interpersonal skills required, including the ability to interact with technical and business users at all levelsRegards!Avinash PathakTel: 212-729-6543 Ext 359Direct: 786-490-0082 |avinash(AT)tanishasystems(DOT)comJob Type: ContractExperience:Product Lifecycle Management: 6 years (Required)Pivot table: 2 years (Required)dashboard: 2 years (Required)PLM: 5 years (Required)

In [0]:
#saved to google drive
simplyhiredjobs.to_csv(path_or_buf='/content/drive/My Drive/simplyhired.csv')

In [0]:
import pandas as pd
jobs = pd.read_csv('/content/drive/My Drive/simplyhired.csv')

In [2]:
jobs[jobs['Title'].str.contains("Data Analyst")]['Salary'].median()

82500.0

In [10]:
jobs[jobs['Title'].str.contains("Data Scientist")]['Salary'].median()

106750.0

In [11]:
jobs[jobs['Title'].str.contains("Junior")]['Salary'].median()

70000.0

In [3]:
jobs[jobs['Description'].str.contains("experience")]

      Unnamed: 0  ...    Salary
6              6  ...   51500.0
12            12  ...   70000.0
14            14  ...   70500.0
19            37  ...   56500.0
30            48  ...   77500.0
...          ...  ...       ...
2720        5388  ...   70500.0
2745        5416  ...       NaN
2747        5418  ...  130000.0
2753        5425  ...  125000.0
2754        5426  ...  140000.0

[425 rows x 6 columns]

In [0]:
[print(x,'\n') for x in jobs['Description']]

In [4]:
jobs['Salary'].isna().sum()
#still 62 nans- will work on that later.

62

In [6]:
jobs[jobs['Title'].str.contains("Junior")]

      Unnamed: 0  ...   Salary
12            12  ...  70000.0
575         1719  ...  70000.0
827         2024  ...  49000.0
1194        2448  ...  53000.0
1754        3671  ...  88500.0
1802        3721  ...  79000.0

[6 rows x 6 columns]

In [7]:
jobs['Business'].nunique()
#count of businesses

868

In [8]:
jobs['Title'].nunique()
#count of job titles unique

1730

In [48]:
jobs['Location'].nunique()

81

In [0]:
quantiles =jobs.groupby('Business')['Salary'].quantile(.5)

In [24]:
quantiles.quantile([.1,.25,.5,.75,.9])
#the quantiles of the median salary per business. median business's median is 83500

0.10     53500.0
0.25     70000.0
0.50     83500.0
0.75     98000.0
0.90    114500.0
Name: Salary, dtype: float64

In [46]:
jobs.groupby('Business',sort=True)['Salary'].median().sort_values()
#lowest paying companies by median salary

Business
Cognosante LLC                   25250.0
St. Louis Park Public Schools    30000.0
DryMAX Solutions                 31500.0
MME Group Inc                    32500.0
Aqseptence Group Inc.            33000.0
                                  ...
SEEK Careers/Staffing                NaN
SLEEP NUMBER                         NaN
Tennant Company                      NaN
The Hartford                         NaN
Travelers                            NaN
Name: Salary, Length: 868, dtype: float64

In [47]:
jobs.groupby('Business',sort=True)['Salary'].median().sort_values(ascending=False)
#highest paying companies by median salary

Business
American Management Services    200000.0
Xceedance                       175000.0
Nexacode                        160000.0
Canopy One Solutions Inc.       160000.0
PwC                             150000.0
                                  ...
SEEK Careers/Staffing                NaN
SLEEP NUMBER                         NaN
Tennant Company                      NaN
The Hartford                         NaN
Travelers                            NaN
Name: Salary, Length: 868, dtype: float64

In [50]:
jobs.groupby('Title',sort=True)['Salary'].median().sort_values(ascending=False)[:25]

Title
Senior Executive Analyst                                                                               200000.0
Director of Product Management – NetBackup                                                             190000.0
Director of Engineering In Home Services and Scheduling                                                185000.0
SVP/VP Chief Actuary                                                                                   175000.0
Engineering Manager - Analysis and Learning Platforms                                                  170000.0
Director of Data Science                                                                               165000.0
Artificial Intelligence Architect Manager - Applied Artificial Intelligence                            162500.0
SAP APO Solution Manager (DP/SNP/GATP)                                                                 160000.0
Senior Data Analytics Manager - Payments - Minneapolis MN                                              155000.0
Applied Artificial Intelligence - Artificial Intelligence - Manager/Architect                          155000.0
Transfer Pricing Senior Manager - Minneapolis                                                          150000.0
Conversational Artificial Intelligence Architect Manager - Applied Artificial Intelligence             150000.0
Senior Manager Business Intelligence                                                                   150000.0
Sr. Software Developer - Java J2EE Big Data                                                            150000.0
Data Governance and Analytics Education Program Director                                               150000.0
AWS Data Warehouse Architect                                                                           150000.0
Capital Planning & Investment Control -Senior Consultant                                               145000.0
VICE PRESIDENT ORIGINATOR – HEALTHCARE/SENIOR LIVING DIRECT LENDING                                    145000.0
Sr. Virtualization Delivery Engineer - Federal                                                         145000.0
Big Data Engineer with some experience in Data Science - Fortune 50 Retailer in Mnpls - 6-12 months    145000.0
Lead Big Data Engineer                                                                                 145000.0
Financial Director - Enterprise Business Intelligence (EBI)                                            145000.0
DoD Senior Software Engineer (North Carolina)                                                          145000.0
Azure Data Engineer                                                                                    145000.0
Data Engineer II                                                                                       145000.0
Name: Salary, dtype: float64

In [52]:
jobs.groupby('Location',sort=True)['Salary'].median().sort_values(ascending=False)[:25]

Location
Lake Elmo MN                   145000.0
Minneapolis MN +2 locations    107500.0
Minnesota                      104500.0
Minneapolis MN +3 locations    102000.0
Richfield MN                   102000.0
Roseville MN                   100250.0
Arden Hills MN +1 location      98000.0
Rogers MN                       96500.0
Apple Valley MN                 96000.0
United States                   96000.0
Cottage Grove MN                95500.0
Edina MN +1 location            95500.0
West Saint Paul MN              95000.0
Brooklyn Center MN              95000.0
Anoka MN                        94750.0
Eden Prairie MN                 94000.0
Saint Louis Park MN             94000.0
Circle Pines MN                 93250.0
Maple Grove MN +1 location      90000.0
Farmington MN                   89500.0
Inver Grove Heights MN          89000.0
Brooklyn Park MN                89000.0
Medina MN                       88500.0
Minneapolis MN                  88000.0
Hudson WI                       87500.0
Name: Salary, dtype: float64

In [23]:
jobs.groupby('Business',sort=True).filter(lambda x: len(x) > 10)['Business'].unique()

array(['Best Buy', 'UnitedHealth Group', 'University of Minnesota',
       'Willis Towers Watson', 'U.S. Bank', 'CHS Inc.',
       'Blue Cross and Blue Shield of Minnesota', 'Allianz Life',
       'FIS Global', 'Horizontal', 'Wells Fargo', 'TARGET',
       'State of Minnesota', 'General Mills', 'Kforce', 'Perficient Inc',
       'Be The Match', 'Ecolab', '3M', 'Cognizant Technology Solutions',
       'Equiniti', 'General Mills Services Inc.', 'Medtronic',
       'Boston Scientific Corporation', 'Medica Health Plans',
       'Abbott Laboratories', 'Fairview Health Services', 'Allina Health',
       'The Toro Company', 'NorthShore Resources Inc.', 'Cargill',
       'C.H. Robinson', 'Target', 'Saudi Aramco', 'Deloitte',
       'CyberCoders', 'Accenture', 'Securian Financial Group',
       'Veritas Technologies'], dtype=object)

In [35]:
#does not have the index function needed to grab the indexes with business names
jobs[jobs['Business'].isin(jobs['Business'].value_counts()>5.index)]

SyntaxError: ignored

I should clean up the salaries because some are still nan, clean up the locations so they are standardized, and clean up the titles so that they are standardized.

In [3]:
jobs['Location'].value_counts()

Minneapolis MN                 1200
Saint Paul MN                   220
Eden Prairie MN                 176
Bloomington MN                  122
United States                    93
                               ...
Saint Paul MN +2 locations        1
Saint Paul MN +13 locations       1
Medina MN                         1
Prior Lake MN                     1
West Saint Paul MN                1
Name: Location, Length: 81, dtype: int64

In [0]:
locations = []
temp = []
counter = 0
doublecount = 0
for location in jobs['Location']:
  for i,inside in enumerate(location) :
    if inside == 'M':
      temp.append('M')
      counter += 1
      continue
      #print(temp)
    if counter == 1:
      print('counter')
      print(inside)
      if inside == 'N':
        locations.append(str(location)[:i-1])
        print('added locat')
        temp = []
        counter = 0
        doublecount +=1
        continue
      else:
        counter = 0
        temp = []
  if doublecount == 0:
    locations.append(location)
  else:
    doublecount = 0
print(locations)

In [34]:
print(len(locations))

2756

In [35]:
locat = pd.DataFrame(locations)
jobs['Location'] = locat
jobs

      Unnamed: 0  ...    Salary
0              0  ...   55500.0
1              1  ...   73000.0
2              2  ...   88000.0
3              3  ...   72000.0
4              4  ...   93500.0
...          ...  ...       ...
2751        5423  ...  111500.0
2752        5424  ...   86000.0
2753        5425  ...  125000.0
2754        5426  ...  140000.0
2755        5428  ...  118000.0

[2756 rows x 6 columns]

In [36]:
jobs[jobs['Location'].isna()]

Empty DataFrame
Columns: [Unnamed: 0, Title, Business, Location, Description, Salary]
Index: []

In [37]:
jobs['Location'].value_counts()[:81]

Minneapolis        1217
Saint Paul          227
Eden Prairie        176
Bloomington         123
United States        93
                   ...
Newport               1
Bayport               1
Falcon Heights        1
Dakota County         1
Medina                1
Name: Location, Length: 69, dtype: int64

In [38]:
jobs[~jobs['Location'].str.contains('MN')]

      Unnamed: 0  ...    Salary
0              0  ...   55500.0
1              1  ...   73000.0
2              2  ...   88000.0
3              3  ...   72000.0
4              4  ...   93500.0
...          ...  ...       ...
2751        5423  ...  111500.0
2752        5424  ...   86000.0
2753        5425  ...  125000.0
2754        5426  ...  140000.0
2755        5428  ...  118000.0

[2756 rows x 6 columns]

In [40]:
jobs['Title'].value_counts()

Business Analyst                                                       68
Data Engineer                                                          22
Software Engineer                                                      22
Business Intelligence Analyst                                          19
Senior Business Analyst                                                17
                                                                       ..
Sr. Sales Commissions Analyst                                           1
Product Performance Engineer II                                         1
QA Engineer                                                             1
Senior Risk Analyst                                                     1
Associate Functional Business Consultant - Networks Client Services     1
Name: Title, Length: 1730, dtype: int64

In [0]:
#important_titles = ['Data','Analyst','Engineering','Analytics','Marketing','Artificial Intelligence','Manager','Architect','Junior','Jr.','Senior','Sr.']
words_that_mean_senior = ['Senior','Sr.','Sr','Lead','Principal','Master','Principle']
words_that_mean_junior = ['Junior','Jr','Jr.','Intern','Associate']
words_that_mean_manager = ['Manager','Director','Management','Superintendent','Architect']
words_that_mean_engineer = ['Engineer','Engineering']
words_that_mean_ai = ['Artificial','AI','Machine','ML']
words_that_mean_data = ['Data','data']
words_that_mean_analyst = ['Analyst','Analytic','Analytics','Intelligence']
words_that_are_jobs = ['Software','Business','Quality','Financial','Product','Sales','Salesforce','Systems','Marketing','Sap','Operations','Scientist','Security','']

In [0]:
from nltk.tokenize import word_tokenize

In [128]:
words = []
for title in jobs['Title']:
  for word in word_tokenize(title):
    words.append(word)
word = pd.DataFrame(words)
word[0].value_counts()[:100]

Analyst           1409
Engineer           778
Business           581
-                  548
Data               481
                  ...
Compliance          17
Electrical          17
Market              17
Infrastructure      17
R                   17
Name: 0, Length: 100, dtype: int64

In [111]:
word[0].value_counts()

Analyst            1409
Engineer            778
Business            581
-                   548
Data                481
                   ...
Cause                 1
eInvestigations       1
WWT                   1
Genomics              1
GRC                   1
Name: 0, Length: 1400, dtype: int64

In [95]:
word_jobs = 'First'
#pattern = '|'.join(mylist)
word_list = [words_that_mean_senior,words_that_mean_junior,words_that_mean_manager,words_that_mean_engineer,words_that_mean_ai,words_that_mean_data,words_that_mean_analyst,words_that_are_jobs]
for j in word_list:
  for t in j :
    word_jobs = word_jobs + '|' + t 
word_jobs

'First|Senior|Sr.|Sr|Lead|Principal|Master|Principle|Junior|Jr|Jr.|Intern|Associate|Manager|Director|Management|Superintendent|Architect|Engineer|Engineering|Artificial|AI|Machine|ML|Data|data|Analyst|Analytic|Analytics|Software|Business|Quality|Financial|Product|Sales|Salesforce|Systems|Marketing|Sap|Operations'

In [56]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [118]:
non_found_words = word[~word[0].str.contains(word_jobs)]
non_found_words[0].value_counts()[120:160]

Portfolio      9
Programmer     9
Pharmacy       9
Account        9
Testing        9
Delivery       9
Controls       9
System         9
ANALYST        9
Credit         9
Model          9
Audit          9
Control        9
Strategy       9
Advanced       9
Designer       9
SQL            8
Billing        8
Site           8
Lab            8
Center         8
Android        8
Medical        8
Access         8
Mnpls          8
HRIS           8
Reliability    8
Accounting     8
Consulting     8
Group          7
Structural     7
Mobile         7
Innovation     7
Desktop        7
Modeling       7
Media          7
Certified      7
Finance        7
Global         7
Corporate      7
Name: 0, dtype: int64

In [0]:
from nltk.stem import WordNetLemmatizer 
  
lemmatizer = WordNetLemmatizer()

In [130]:
lemmatized = []
for worded in word[0]:
  lemmatized.append(lemmatizer.lemmatize(worded))
pd.DataFrame(lemmatized)

               0
0           Data
1        Analyst
2      Marketing
3           Data
4        Analyst
...          ...
12061          (
12062       Full
12063      Stack
12064  Developer
12065          )

[12066 rows x 1 columns]

In [0]:
lemma = pd.DataFrame(lemmatized)

In [134]:
lemma[0].value_counts()

Analyst      1409
Engineer      778
Business      581
-             548
Data          481
             ...
Setup           1
AC4             1
SUPPORT         1
Veeva           1
Temporary       1
Name: 0, Length: 1400, dtype: int64

In [0]:
#lemmatizing did not make the amount of words less meaning I still have to go by hand and find words that mean the same or similar thing in order
#to consolidate the amount of titles